services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    networks:
      - laravel
    volumes:
      - .:/var/www
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: bwell_work
      MYSQL_USER: bwell_work
      MYSQL_PASSWORD: bwell_work
      MYSQL_ROOT_PASSWORD: bwell_work
      MYSQL_SSL_MODE: DISABLED  # Add this line to disable SSL
    ports:
      - "3307:3306"
    networks:
      - laravel

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
