version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor  # Persist vendor directory (important in Coolify)
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: mysql
      MYSQL_PASSWORD: "6sXDBkduDCLwKaTXH9weDhEnwjNIWWsioosKPAVAKGbbolKwAlQ37y2GUzGNbCD5"
      MYSQL_ROOT_PASSWORD: "StrongRootPassword123!"
    ports:
      - "5433:5432"
    networks:
      - laravel
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data in Coolify

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d:ro  # Ensure this file exists
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
