name: Deploy Node.js Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3


      # Deploy to the server and build Docker image there
      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          password: ${{ vars.SSH_PASSWORD }} # Or use `private-key`
          source: "./"
          target: ${{ vars.DEPLOY_PATH }} # Replace with your target directory on the server

      # SSH into the server and build
      - name: Composer
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ vars.SERVER_USER }}
          password: ${{ vars.SSH_PASSWORD }} # Or use `private-key`
          script: |
            cd ${{ vars.DEPLOY_PATH }}
            composer install
            sudo chown -R vito:vito ${{ vars.DEPLOY_PATH }}
            sudo chmod -R 755 ${{ vars.DEPLOY_PATH }}
